# Generated by Django 3.2.6 on 2021-08-31 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', djrichtextfield.models.RichTextField()),
                ('author_ans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', djrichtextfield.models.RichTextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('n_comments', models.IntegerField()),
                ('n_answers', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('upvotes_ques', models.ManyToManyField(related_name='upvotes_ques', to=settings.AUTH_USER_MODEL)),
                ('views', models.ManyToManyField(related_name='views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time', models.DateField(auto_now_add=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='StackOverflow.answers')),
                ('author_cmnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cmnt', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_cmnt', to='StackOverflow.questions')),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_ans', to='StackOverflow.questions'),
        ),
        migrations.AddField(
            model_name='answers',
            name='upvotes_ans',
            field=models.ManyToManyField(related_name='upvotes_ans', to=settings.AUTH_USER_MODEL),
        ),
    ]
