# Generated by Django 3.2.6 on 2021-09-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StackOverflow', '0006_auto_20210913_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='n_answers',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='n_comments',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
