# Generated by Django 3.2.6 on 2021-09-25 13:18

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StackOverflow', '0010_auto_20210925_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default=builtins.id, max_length=50),
        ),
    ]
