# Generated by Django 3.2.6 on 2021-09-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StackOverflow', '0011_alter_question_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
    ]
